### ISSUE TITLE
Possible to maintain multiple boilerplates, one with the simpler setup from before and one with the current?

### ISSUE THREAD

**Issue by AustinWinstanley** [pauldotknopf/react-dot-net#2]
This boilerplate is great. But the current version is much more involved than the previous.

https://github.com/pauldotknopf/react-aspnet-boilerplate/tree/58b38cc45c712f261668bd582599ae59e0b583c5

Would it be possible to maintain both, the much simpler one for a basic setup/learning, and then the more complicated for a more advanced setup?

**Comment by AustinWinstanley** [comment]
This could actually lead to multiple boilerplate setups for different purposes. A single setup is tough to cover different purposes without getting overly complicated. I'm happy to help.

**Comment by pauldotknopf** [comment]
> This boilerplate is great. But the current version is much more involved than the previous.

I agree. However, my argument for having it more complicated is that it demonstrates _how_ things are to be done, by example.

For example, [react-redux-universal-hot-example](https://github.com/erikras/react-redux-universal-hot-example) has surveys, login/logout, chat, widgets, etc, all built in to the boilerplate. The user using the boilerplate would delete the functionality they don't need when starting.

My idea was to implement the aspnet starter project that "File > New Project" in Visual Studio gives you to help users get an idea of how to use it. This would work as an example that users can actually use, instead of the useless survey/chat/widget stuff in [react-redux-universal-hot-example](https://github.com/erikras/react-redux-universal-hot-example).

With that said, I am not opposed to maintaining two branches. A `master` branch that is super clean, and a `aspnet-starter-template` branch that has all the bells and whistles. However, instead of reverting to an older commit for a branch, I rather start a new branch and remove what is deemed non-essential for a basic setup. The reason why is because as I was implementing the aspnet login/logout/register, I fixed some things, and added some things that even a basic setup will need/want. For example, these following changes have been made that I would like to be in the basic setup.

> Added react-redux-router (9cb8188d)
> Added redux router middle ware to the store so that we can fire navigation commands through redux. (bf8c0fde)
> Simplified the redux store with clientMiddleware (just like in react-redux-universal-hot-example) (https://github.com/pauldotknopf/react-aspnet-boilerplate/tree/1bdfa66/src/React/Scripts/redux)

What are your thoughts? What exactly are you thinking about for this basic `master` branch? No account management? Just simple static pages?

**Comment by pauldotknopf** [comment]
I created an empty template with the minimal recommend functionality. Check the [empty-template](https://github.com/pauldotknopf/react-aspnet-boilerplate/tree/empty-template) branch.
