### ISSUE TITLE
Alternative.

### ISSUE THREAD

**Issue by jdosullivan** [pauldotknopf/react-dot-net#27]
Couldn't quite get this to work with hot module reloading.

Found this: http://blog.stevensanderson.com/2016/05/02/angular2-react-knockout-apps-on-aspnet-core/

Scaffolds out with yeoman and works beautifully on the first go with universal rendering, hot reload, .net core, webpack ... the works.

**Comment by pauldotknopf** [comment]
I will update this repo to include it soon, it is an easy add. The libraries we are using ([`JavaScriptViewEngine`](https://github.com/pauldotknopf/JavaScriptViewEngine)) supports HMR.

There is a sample project using HMR/React [here](https://github.com/pauldotknopf/JavaScriptViewEngine.Samples/tree/master/src/Sample.MvcCore1.ReactHotModuleReloading). You can use it as a reference to update this repo yourself. The pieces you will want to pay attention to are [here](https://github.com/pauldotknopf/JavaScriptViewEngine.Samples/blob/eb2fb96/src/Sample.MvcCore1.ReactHotModuleReloading/Startup.cs#L60), [here](https://github.com/pauldotknopf/JavaScriptViewEngine.Samples/blob/eb2fb964a54d28fcdd3f50c61c5ae795c69ef240/src/Sample.MvcCore1.ReactHotModuleReloading/.babelrc#L3) and [here](https://github.com/pauldotknopf/JavaScriptViewEngine.Samples/blob/eb2fb964a54d28fcdd3f50c61c5ae795c69ef240/src/Sample.MvcCore1.ReactHotModuleReloading/gulpfile.js).

You can also use that sample project if you don't wish to have the authentication/membership implementation in this repo.

**My two-cents:**

You really shouldn't rely on finding a boilerplate to meet your exact needs. That is like only having 10 different models of houses. No family will ever find a house they are 100% happy with. Instead, you should rely on the other "houses" as inspiration to build your own home.

With that said, using [JavaScriptViewEngine](https://github.com/pauldotknopf/JavaScriptViewEngine) gives you the most freedom of using Node with .NET so that you can build whatever you like, without opinions. The boilerplate you mentioned (hosted at [JavaScriptServices](https://github.com/aspnet/JavaScriptServices) is very opinionated. Imagine it like bowling, but with the gutter rails up. The moment you need anything other than what is prescribed in the boilerplate, you will find yourself going against the grain. You shouldn't have to spend time learning the tools. With `JavaScriptViewEngine`, everything is raw, without opinions, while being completely flexible.

So, instead, use [JavaScriptViewEngine](https://github.com/pauldotknopf/JavaScriptViewEngine) (samples [here](https://github.com/pauldotknopf/JavaScriptViewEngine.Samples/tree/master/src)) and build your own project with whatever you like. React/Angular/Aurelia/HMR/server-rendering/react-router/etc.

**Comment by jdosullivan** [comment]
As much as I want to agree with you here I have to disagree. I would much rather start out with an opinionated boilerplate that works but is clear with respect to the pieces it's using and why.  The main problem with boilerplates these days is that they provide a basic foundation out of the gate that works well and using your house example, as soon as you decide to put on a door or add something simple you end up in a world of hurt. 

I applaud your efforts on this task you've taken on but it broke down for me when it came to tracking down HMR issues and deploying to Azure. By contrast the boilerplate I mentioned, though opinionated, uses industry standard Microsoft-backed pieces that simply work out of the gate.
